[build]
target = "avr-specs/avr-atmega328p.json"
#target = "avr-none"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 115200 -P /dev/ttyUSB0"
#rustflags = ["-C", "target-cpu=atmega1280", "-C", "default-linker-libraries"]
rustflags = ["-C", "link-args=-Wl,--allow-multiple-definition", "-lm"]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
